name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]
  workflow_dispatch:

env:
  USE_BAZEL_VERSION: "6.4.0"

jobs:
  build_and_test:
    if: contains(github.event.pull_request.labels.*.name, 'do-macos-build') || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Build & Test
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87.0

      - name: Verify Installations
        run: |
          echo "--- Bazel Version ---"
          bazel --version
          echo "--- Rust Version ---"
          rustc --version
          cargo --version

      - run: cargo check --workspace --all-targets
      - run: cargo build --workspace --all-targets
      - run: cargo test --workspace --all-targets
      - name: Test with all features
        run: cargo test --workspace --all-targets --all-features
